#!/bin/bash

if (( $# < 2 )); then
	echo "Usage: $0 <file location of file, read line by line, line termination by newline character>"
	exit 1
fi

function __enqueue_download_from_file()
{
	local force_download=false
	local create_from_template=false

	# parse commandline options
	getopt --test > "/dev/null" &&:
	if (( $? != 4 )); then
		echo>&2 "ERROR: 'getopt --test' failed in this environment!"
		exit 1
	fi

	local long_options="force,create-from-template"
	local short_options=""
	local parsed_options=$(getopt --options="$short_options" --longoptions="$long_options" --name "$0" -- "$@") || exit 2
	eval set -- "$parsed_options"

	while :; do
		case "$1" in
			-f|--force)
				force_download=true
				shift
				;;
			--create-from-template)
				create_from_template=true
				shift
				;;
			--)
				shift
				break
				;;
			*)
				echo>&2 "ERROR: Programming error!"
				exit 1
				;;
		esac
	done

	if [[ "$force_download" == "true" ]]; then
		force_download=true
	else
		force_download=false
	fi
	if [[ "$create_from_template" == "true" ]]; then
		create_from_template=true
	else
		create_from_template=false
	fi

	local queue_name="$1"
	shift ||__expression_may_fail

	local template_name="$1"
	shift ||__expression_may_fail

	local sources_full_file_real_path="$1"
	shift ||__expression_may_fail

	local download_index="$1"
	shift ||__expression_may_fail

	local queue_full_file_path=""

	if $create_from_template; then
		queue_full_file_path="$queue_name-$__current_date.queue"
		cp -- "$__script_path/templates/$template_name.template" "$queue_full_file_path"
		queue_full_file_path=":$queue_full_file_path"
	fi

	local stop_marker_found=false

	local url
	while read -r url; do
		if [[ "${url:0:2}" == "##" ]]; then
			stop_marker_found=true
			continue
		fi

		if [[ "$url" == "" || "${url:0:1}" == "#" ]] || $stop_marker_found; then
			continue
		fi

		if $force_download; then
			enqueue-download "${template_name}$queue_full_file_path" "$url" "--download-archive=$download_index"
		else
			enqueue-download "${template_name}$queue_full_file_path" "$url"
		fi
	done < "$sources_full_file_real_path"

	__queue_selector="${template_name}$queue_full_file_path"
	export __queue_selector
}

__enqueue_download_from_file "$@"
