#!/bin/bash

set -uo pipefail -o noclobber -o nounset
#set -euxo pipefail
shopt -s inherit_errexit
#set -x

handle_error() {
	# @source https://gist.github.com/bkahlert/08f9ec3b8453db5824a0aa3df6a24cb4
	local esc_red esc_reset; esc_red=$(tput setaf 1 ||__expression_may_fail); esc_reset=$(tput sgr0 ||__expression_may_fail)
	printf "%s %s\n\tin program:\t %s\n\tat location:\t %s\n\tat line:\t %s\n" "${esc_red-}✘${esc_reset-}" "${esc_red-}$(errno "$1" )${esc_reset-}" "${0##*/}"  "$3" "$2" >&2
	exit "$1"
}

trap 'handle_error "$?" "${BASH_COMMAND:-?}" "${FUNCNAME[0]:-main}(${BASH_SOURCE[0]:-?}:${LINENO:-?})"' ERR
#trap 'echo Program failed! Error at line $LINENO' ERR

sudo apt install moreutils

if [[ ! -e "configuration/defaults" ]]; then
	cp "configuration/defaults.example" "configuration/defaults"
fi

source -- "configuration/defaults" || exit 1

if [[ ! -d "$application_var_directory/queues" ]]; then
	mkdir --parents -- "$application_var_directory/queues"
	cp "installation/queues-templates/"* "$application_var_directory/queues"
fi

mkdir --parents "$HOME/applications"
echo 'source -- "$HOME/applications/undownloader/configuration/aliases"' >> "$HOME/.bash_aliases"
echo 'PATH="$HOME/applications/undownloader/bin:$PATH"' >> "$HOME/.bashrc"

set +x
echo -ne "\n\nSUCCESS!\n\n"
