#!/bin/bash

if (( $# == 0 )); then
	echo "Usage: $0 <queue name> <data>"
	echo "Usage: $0 <queue template name>:<queue file location> <download URL>"
	exit 1
fi

source -- "$(realpath "$(dirname -- "${BASH_SOURCE[-1]}")/../")/library/base"
__set_script_path
__enable_error_handler
source -- "$__script_path/configuration/defaults"

force=false
if [[ "$1" == "--force" ]]; then
	force=true
	shift ||:
fi

if [[ -z "$1" ]]; then
	__error "queue file not given"
	__exit_failsafe
fi

template_name="${1%:*}"
queue_full_file_path="${1#*:}"

if [[ "$queue_full_file_path" == "$template_name" ]]; then
	queue_file="$application_var_directory/queues/$template_name.queue"
else
	queue_file="$queue_full_file_path"
	# @fixme verify if given $1 = "axudio:/home/ju/Daten1/var/undownloader/application/queues/foobar_music.queue"
	# that $template_name axudio is the correct template name for the queue (which it is not, the string is erroneously accepted)
fi

if [[ ! -f "$queue_file" ]]; then
	__error "queue file '%s' does not exist" "$queue_file"
	__exit_failsafe
fi

queue_name="$queue_full_file_path"
shift ||:

function handle_line() {
	parameters=()

	#echo "1=${1:-?}"
	#echo "2=${2:-?}"
	#echo "3=${3:-?}"
	#echo "4=${4:-?}"

	#read -ra parameter_input_array <<< "$@"
	#for parameter in "${parameter_input_array[@]}"; do
	for parameter in "$@"; do
		parameters+=( "\"$parameter\"" )
	done

	item_count="${#parameters[@]}"

	if ! $force; then
		line="${parameters[*]}"
	else
		line="${parameters[*]} --download-archive=archive/$__current_date.memory"
		((item_count++))||:
	fi

	line="$((2+item_count)) $line -- " # item_count +2 because: "––" and item_count itself are counted as two additional items

	# source: https://blog.stigok.com/2018/05/31/surprising-sed-replace-uri-with-ampersand.html
	# escape certain characters
	line=$(sed 's/[&/\]/\\&/g' <<< "$line")

	# source: https://unix.stackexchange.com/questions/188264/how-do-i-substitute-only-first-occurence-with-sed
	# insert download data below top-most "+ \" insertion marker, but none other if existing
	sedex="/^+ \\\/{s//+ \\\\\n$line\\\/;:p;n;bp}"
	sed -i "$sedex" "$queue_file" && echo "The url '${parameters[0]}' is appended to queue '$queue_name'."

	# link-muddler-delete-link "${parameters[0]}" #@fixme
}

if [[ -z "${1:-}" ]]; then
	previous_line="?"
	echo "No data provided, entering INPUT MODE, use linebreak to exit"

	while true; do
		read -r line
		mapfile -t lines < <(xargs -n1 printf '%s\n' <<< "$(__trim_string_balanced "$line" \")")
		set -- "${lines[@]}"

	#echo "1=${1:-?}"
	#echo "2=${2:-?}"
	#echo "3=${3:-?}"
	#echo "4=${4:-?}"
	#echo "l=$# a=$*"

		if (( $# > 0 )) && [[ $1 != "" ]]; then
			handle_line "$@"
		else
			line=""
		fi

		if [[ "${previous_line}${line}" == "" ]]; then #both are empty
			break
		fi

		previous_line="$line"
	done
else
	#echo "1=${1:-?}"
	#echo "2=${2:-?}"
	#echo "3=${3:-?}"
	#echo "4=${4:-?}"
	#echo "l=$# a=$*"

	handle_line "$@"
fi

