#!/bin/bash

function get_library_path()
{
	local former_directory
	former_directory="$(pwd)"

	local source="${BASH_SOURCE[0]}"
	while [[ -L "$source" ]]; do # resolve $source until the file is no longer a symlink
		local directory
    	directory="$(cd -P "$(dirname -- "$source")" > "/dev/null" 2>&1 && pwd)"

		source="$(readlink -- "$source")"
		[[ "$source" != /* ]] && source="$directory/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
	done

	cd -P "$(dirname -- "$source")/../" > "/dev/null" 2>&1 && pwd
	cd -- "$former_directory" || exit 1
}

UNDOWNLOADER_LIBRARY_PATH="$(get_library_path)"

function d() {
	local queue_name
	queue_name="${1:-}"
	shift ||__expression_may_fail

	__call_handler "enqueue" "$queue_name" "$@"
}

function dv() {
	__call_handler "enqueue-video" "$@"
}

function dav() {
	__call_handler "enqueue-audio+video" "$@"
}

function da() {
	__call_handler "enqueue-audio" "$@"
}

function __call_handler() {
	handler_name="$1"
	shift ||__expression_may_fail

	PATH= /bin/env --ignore-environment HOME="$HOME" USER="$USER" XDG_SESSION_ID="$XDG_SESSION_ID" /bin/bash -ci 'exec "$0" "$@"' "$UNDOWNLOADER_LIBRARY_PATH/handlers/$handler_name" "$@" ||__expression_may_fail
	# old alternatives, less fine
	#PATH= /bin/env -u PATH /bin/bash -ci 'exec "$0" "$@"' "$UNDOWNLOADER_LIBRARY_PATH/handlers/$handler_name" "$@" ||__expression_may_fail
    #PATH= /bin/env --ignore-environment HOME="$HOME" USER="$USER" XDG_SESSION_ID="$XDG_SESSION_ID" /bin/bash -ci -- '"'$UNDOWNLOADER_LIBRARY_PATH'/handlers/$handler_name" "$0" "$@"' "$@" ||__expression_may_fail
}
